### ISSUE TITLE
Element font color changes to node font color when shapes are removed

### ISSUE THREAD

**Issue by mooreek** [spielmanlab/dragon#4]
When I remove the shapes for the element nodes the element font color changes from black to the color of the element node shape color.  This not a big issue because I could just change the element node shape color to black and it changes the element node font color to black, but it was confusing at first.

**Comment by sjspielman** [comment]
Yeah, this was a tricky situation, and it may be that the current use is not ideal. Because there is no node color attribute when shapes are removed, AND because it is not possible to set color schemes to font colors (only node colors), I have assigned node color --> font color when shapes are disabled.
If this doesn't work for you I can disable this feature have text color controlled exclusively by font color, but this will mean any kind of node color scheme (i.e. color by degree or redox) will not be reflected in node text when shapes are removed. Let me know your preference and I'll edit from there.

**Comment by sjspielman** [comment]
Bug (most likely) fixed. Closing this issue; please reopen or file a new issue if I have broken everything...
